chat/urls.py
# chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:room_number>', views.room, name='room'),
    path('newRoom/<int:pk>', views.newRoom, name='newRoom'),
    path('send/', views.send, name='send'),
    path('getMessages/<int:room_number>', views.getMessages, name='getMessages'),
]

dmnproject/urls.py
# dmnproject/urls.py
from django.contrib import admin
from django.urls import path, include
# for uploading media files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('accounts.urls')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
]

# for uploading media files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/<str:category>', views.home, name="home"),
    path('new/', views.new, name="new"),
    path('detail/<int:pk>', views.detail, name="detail"),
    path('edit/<int:pk>', views.edit, name="edit"),
    path('detail/<int:pk>/delete', views.delete, name="delete"),
    path('search/', views.SearchFormView.as_view(), name="search"),
    path('participated/<int:pk>/', views.post_participated_toggle, name="post_participated_toggle"),
]

main/models.py
# main/models.py
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from accounts.models import Profile
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit


class Post(models.Model):
    objects = models.Manager()
    author = models.ForeignKey(Profile, blank=True, null=True,
                               on_delete=models.CASCADE, related_name='author_post')
    category = models.CharField(max_length=20,
                                choices=(
                                    ('Offline', '오프라인'),
                                    ('Online', '온라인'),
                                    ('Delivery', '배달음식'),
                                ))
    title = models.CharField(max_length=150)
    pub_date = models.DateTimeField(default=timezone.now)
    body = models.TextField(default='')
    region = models.CharField(max_length=50, blank=True, null=True)
    item = models.CharField(max_length=50)
    limit = models.PositiveIntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(10)])
    link = models.URLField(max_length=300, blank=True, null=True)
    deadline = models.DateTimeField(blank=True, null=True)
    members = models.ManyToManyField(
        Profile, blank=True, related_name='members_post')
    # 사진 1개 받기
    image = ProcessedImageField(
    		blank = True,
        	upload_to = 'post/images',
        	processors = [ResizeToFit(300, 300)],
        	format = 'JPEG',
        	options = {'quality':90},
    		)

    def __str__(self):
        return self.title


# 사진 여러개 받기
# class Images(models.Models):
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     image = ProcessedImageField(
#         blank=True,
#         upload_to='post/images',
#         processors=[ResizeToFit(300, 300)],
#         format='JPEG',
#         options={'quality': 90},
#     )

main/forms.py
# main/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'item','link','category','limit','deadline',
        'body', 'image']
        labels = {
            'title':'제목',
            'category':'카테고리',
            'body':'본문',
            'item':'품목',
            'limit':'모집인원',
            'link':'링크',
            'deadline':'마감기한',
            'image':'사진'
        }


class PostSearchForm(forms.Form):
    category = forms.CharField(label='Category')
    search_word = forms.CharField(label='Search Word')

main/views.py
# main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Post
from .forms import PostForm, PostSearchForm
from django.db.models import Q
from django.views.generic import FormView
from django.contrib.auth.decorators import login_required
from chat.views import sendNotice


def home(request, category):
    # 카테고리별 게시글
    if category == 'All':
        posts_list = Post.objects.all()
    else:
        posts_list = Post.objects.all().filter(category=category)
    # 참가중인 채팅방
    posts_participated = request.user.profile.post_participated.all()
    # 마감임박 게시글
    posts = Post.objects.all()
    for post in posts:
        if post.members.count() != post.limit - 1 or posts_participated.filter(pk=post.pk):
            posts=posts.exclude(pk=post.pk)
    posts_orderby_deadline = posts.order_by('deadline')
    return render(request, 'home.html', {'posts_list': posts_list, 'posts_participated': posts_participated, 'posts_orderby_deadline': posts_orderby_deadline, 'category': category})


# CRUD

@login_required
def new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user.profile
            post.published_date = timezone.now()
            post.region = request.user.profile.address
            post.save()

            # 게시글을 작성하면 자동으로 공구에 참여
            post.members.add(post.author)
            post.author.post_participated.add(post)

            # 게시글을 생성하고 곧바로 채팅방 생성을 위해 newRoom 함수로 이동
            return redirect('chat:newRoom', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'new.html', {'form': form})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'detail.html', {'post': post})


def edit(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 작성자만 수정할 수 있도록 함
    if request.user != post.author.user:
        return redirect('detail', pk=post.pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user.profile
            post.published_date = timezone.now
            post.save()
            return redirect('detail', pk=post.pk)
    else:
        # 이후에 프론트에서의 수정방식에 따라 form = post로 변경
        form = PostForm(instance=post)
    return render(request, 'edit.html', {'form': form})


def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 작성자만 삭제할 수 있도록 함
    if request.user != post.author.user:
        return redirect('detail', pk=post.pk)

    post.delete()
    return redirect('home', 'All')


# Search

class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'home.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']

        # 카테고리별로 보기
        if (category := self.request.POST.get('category')) != 'All':
            posts = Post.objects.all().filter(category=category)
            post_list = posts.filter(Q(title__icontains=searchWord) | Q(
                body__icontains=searchWord) | Q(deadline__icontains=searchWord)).distinct()
        # 전체보기
        else:
            post_list = Post.objects.filter(Q(title__icontains=searchWord) | Q(
                body__icontains=searchWord) | Q(deadline__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['posts_list'] = post_list
        context['category'] = category

        return render(self.request, self.template_name, context)


# 공구 참여

@login_required
def post_participated_toggle(request, pk):
    post = get_object_or_404(Post, pk=pk)
    profile = request.user.profile

    # 글쓴이는 공구 참여/취소 버튼을 누를 필요가 없으므로 detail 페이지로 redirect
    if profile == post.author:
        return redirect('detail', pk)

    check_participated_post = profile.post_participated.filter(pk=pk)

    # 공구에 이미 참여중인 경우 공구 취소 버튼이 작동
    if check_participated_post.exists():
        sendNotice(profile.nickname + "님이 채팅방을 나갔습니다. (%d/%d)"%(post.members.count()-1, post.limit), pk)
        post.members.remove(profile)
        profile.post_participated.remove(post)
        post.save()
    # 공구에 아직 참여하지 않았고 모집인원이 남아있는 경우 공구 참여 버튼이 작동
    elif post.members.count() < post.limit:
        sendNotice(profile.nickname + "님이 채팅방에 입장했습니다. (%d/%d)"%(post.members.count()+1, post.limit), pk)
        post.members.add(profile)
        profile.post_participated.add(post)
        post.save()
    return redirect('detail', pk)

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
</head>

<body>
    <header>
        <a href="{% url 'home' 'All' %}">
            <b class="logo">동네에서 만나요</b>
        </a>
        
        <!-- 프로필 이미지 base.html에서 받아오기...... -->
        
        <div class="profile-container">
            {%if user.profile.my_image%}
            <img class="profile-img" src="{{ user.profile.my_image.url }}" alt="profile"> <!--여기 이미지가 안받아지네.. 좀따 확인-->
            {% else %}
            <img class="profile-img" src="{% static 'main/img/profile.png' %}" alt="profile">
            {%endif%}
        </div>
        <div class="nickname"> "{{ user.profile.nickname }}" 님 환영해요!</div>

        <a href="{% url 'profile' username=user %}"><button class="logout">마이페이지</button></a>
        <a href="{% url 'logout' %}"><button class="logout">로그아웃</button></a>
        
    </header>

    {% block content %}
    {% endblock %}

</body>

</html>

main/templates/detail.html
<!--main/templates/detail.html-->
{% extends 'base.html' %}

{% load static %}
{% load bootstrap4 %}
{% block content %}


<!DOCTYPE html>
<html lang="en">

<head>
    <title>Detail_1</title>
    <!-- <link rel="stylesheet" href="./style.css"> -->
    <link rel="stylesheet" href="{% static 'accounts/css/detail.css' %}">
</head>


    
  <!--
    <hr>
    <main>
        <section class="boxtop">
            <b>제목</b>
            <div class="writer">
                <img src='./iconmonstr-user-6-240.png' alt="myprofile" width=30px, height=30px>
                작성자
            </div>
        </section>
        <hr align="center" width="80%" size="5" color="green" noshade />
        <form>
            <section class="inputs">
                <div class="name_input">
                    <label for="location">지역</label>
                    <input type="text" readonly id="location" name="location">
                </div>
                <div class="name_input">
                    <label for="link">링크</label>
                    <input type="text" readonly id="link" name="link">
                </div>
                <div class="name_input">
                    <label for="item">품목</label>
                    <input type="text" readonly id="item" name="item">
                </div>



<hr>-->



<!-- /////////////////////// -->
<head>
    <title>Detail</title>
    
    <link rel="stylesheet" href="{% static 'main/css/detail.css' %}">
</head>
<main>
    
    <section class="boxtop">
        <b>{{ post.title }}</b>
        <div class="writer">
            작성자 : {{post.author}}
        </div>
    </section>
    <hr align="center" width="80%" size="5" color="green" noshade />
    
        <section class="inputs">
            <div class="name_input">
                <label for="link">구분</label>
                <div class="input" type="text" readonly id="location" name="location">{{ post.category }}</div>
            </div>
            <div class="name_input">
                <label for="link">링크</label>
                <div class="input" type="text" readonly id="link" name="link"><a href="{{post.link}}" target=_blank>{{post.link}}</a></div>
            </div>
            <div class="name_input">
                <label for="item">품목</label>
                <div class="input" type="text" readonly id="item" name="item">{{ post.item }}</div>
            </div>
            <div class="name_input">
                <div class="dead">
                    <label for="deadline">마감기한</label>
                    <div class="input" type="datetime-local" id="deadline" name="deadline">{{ post.deadline }}</div>
                </div>
            </div>
            <div class="name_input">
                <label for="people">정원</label>
                <div class="input" type="text" readonly id="people" name="people"> {{ post.members.count }}/{{ post.limit }}</div>
            </div>
            {% if post.image %}
            <button class="image-button" onclick="viewImage()">이미지 보기</button> 
            {% endif %}
            
        </section>
        
        <!-- 이 부분 이미지 변수 확인---------------------------------------------------------------------------------------------------------------------------------------- -->
        {% if post.image %}
        <img class="content-image"src="{{ post.image.url}}" alt="img">
        <button class="cancel" onclick="closeImage()">x</button>
        {% endif %}
        <div class="input" type="text" readonly id="bodytext" name="bodytext" placeholder="본문 내용">{{ post.body }}</div>

            
        
        <h3 id="part-text">참가자</h3>

        <section class="member">
                        
                
                    
                    {% for member in post.members.all %}
                    <div class="participant">
                        <div class = "memimg">
                            {% if member.my_image %}
                            <img src='{{member.my_image.url}}' alt="myprofile" width=40px, height=40px style="margin:auto; min-width:100%; min-height:100%;">
                            {% else %}
                            <img src='{%static "main/img/profile.png"%}' alt="myprofile" width=40px, height=40px>
                            {% endif %}

                        </div>
                            <p> -{{member}}</p>
                            
                    </div>
                    
                    {% endfor %}
                    
                    
                
            
            <!-- 여기서부터 -->
            
        </section>
        <div class="btmbox">
            
            {% if user.profile in post.members.all %}
            
                <a href="{% url 'chat:room' room_number=post.pk %}" ><button class="btn">채팅방 입장</button></a>
                {% if post.author == user.profile %}
                    <a href="{% url 'edit' pk=post.pk %}"><button class="btn">EDIT</button>  </a>
                    <a href="{% url 'delete' pk=post.pk %}"><button class="btn">DELETE</button> </a>
                {% endif %}
            
            {% else %}

            {% if user.is_authenticated and user.profile != post.author %}
                <a href="{% url 'post_participated_toggle' post.pk %}" class="btn btn-outline-success mr-5">
                    {% if user.profile in post.members.all %}
                    <button class="btn">취소</button>
                    {% elif post.members.count >= post.limit%}
                    <button class="btn" disabled>모집완료</button>
                    {% else %}
                    <button class="btn">공구 참여하기</button>
                    {% endif %}
                </a>
            {% endif %}

            {% endif %}




            </div>
    <script>
        function viewImage(){
            document.querySelector(".content-image").style.display="block";
            document.querySelector(".cancel").style.display="block";
        }

        function closeImage(){
            document.querySelector(".content-image").style.display="none";
            document.querySelector(".cancel").style.display="none";
        }
    </script>
</main>

{% endblock %}

main/templates/edit.html
<!--main/templates/edit.html-->
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Edit</title>
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/edit.css' %}">
</head>

<body>
    <div class="container">
        <div inputs>
            <form method="POST" enctype="multipart/form-data">
                <div class="inform">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="save btn btn-default">글 수정하기</button>
                </div>
            </form>
        </div>
    </div>
</body>
{% endblock %}

</html>

main/templates/home.html
<!--main/templates/home.html-->

{% extends 'base.html' %}
{% load static %}
{% block content %}






<!-- /////////////////////////////////////////////// -->



<head>

    <title>Main</title>
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>

<body>
    <!-- 여기부터 메인 -->
    <main class="main-main"></main>
    <!-- 애니메이션 화면  -->

    <div class="first">
        <!-- 검색창 -->

        <form action="{% url 'search' %}" method="post" class="search-container">
            {% csrf_token %}
            <input type="hidden" name="category" label="Category" value="{{category}}">
            <div class="search-box">
                <input type="text" name="search_word" label="Search Word" placeholder="공동구매할 상품을 검색하세요.">
                <button type="submit" value="Submit"> 검색 </button>
            </div>
        </form>
        <a href="{% url 'new'  %}"><button style="position:absolute; right:12%; ">글쓰러 가기</button></a>


        <!-- 카테고리 -->
        <div class="category-box">
            <a href="{% url 'home' 'All' %}">전체글</a>
            <a href="{% url 'home' 'Offline' %}">오프라인</a>
            <a href="{% url 'home' 'Online' %}">온라인</a>
            <a href="{% url 'home' 'Delivery' %}">배달</a>

        </div>

        <!-- 검색결과 박스 -->
        <div class="result-box">
            {% if posts_list %}
            {% for post in posts_list %}
            <div class="details">
                <div class="detail_cate">
                    <a href="{% url 'detail' pk=post.pk %}" class="in-result-box">
                        <p class="c">{{ post.category }}</p>
                    </a>
                </div>
                <div class="detail_preview">
                    <a href="{% url 'detail' pk=post.pk %}" class="in-result">
                        <p class="t1">{{ post.title }}</p>
                        <p class="a1">{{ post.author }}</p>
                        <p class="i1"> [{{post.item}}]</p>
                        <p class="mem1">{{ post.members.count }}/{{ post.limit}}</p>
                    </a>
                </div>
            </div>
            {% endfor %}

            {% elif search_term %}
            <!--검색란이 공란인지 확인 -->
            <b>"({{ search_term }})"에 대한 검색결과가 없습니다. 새로운 글을 작성해 보시는 건 어떨까요?</b>

            {% endif %}
        </div>
    </div>

    <div class="second">
        <h2>참여중인 대기방</h2>
        <div class="my-group">
            {% if posts_participated %}
            {% for post in posts_participated %}
            <div class="my-room">
                <div class="chat_preview">
                    <a href="{% url 'detail' pk=post.pk %}" class="in-result-box3">
                        <p class="c">{{ post.category }}</p>
                        <p class="t">{{ post.title }}</p>
                        <p class="a">{{ post.author }}</p>
                        <p class="i"> [{{post.item}}]</p>
                        <p class="m">{{ post.members.count }}/{{ post.limit}}</p>
                    </a>
                </div>
                <div class="detail_cate2">
                    <a href="{% url 'chat:room' room_number=post.pk %}" class="in-result-box">
                        <button>채팅방 입장</button>
                    </a>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>

        <div class="third">
            <h2>추천 대기방</h2>
            <div class="rec-room-list"></div>
            {% if posts_orderby_deadline %}
            {% for post in posts_orderby_deadline %}
            <div class="details">
                <div class="detail_cate">
                    <a href="{% url 'detail' pk=post.pk %}" class="in-result-box">
                        <p class="c">{{ post.category }}</p>
                    </a>
                </div>
                <div class="detail_preview">
                    <a href="{% url 'detail' pk=post.pk %}" class="in-result-box2">
                        <p class="t">{{ post.title }}</p>
                        <p class="a">{{ post.author }}</p>
                        <p class="i"> [{{post.item}}]</p>
                        <p class="m">{{ post.members.count }}/{{ post.limit}}</p>
                    </a>
                </div>
            </div>

            {% endfor %}
            {%else%}
            <br>
            아직 추천해드릴 대기방이 없어요 ㅠㅠ 새로 글을 써보시는 건 어떨까요?
            {% endif %}

        </div>


        </main>
</body>

{% endblock %}

main/templates/new.html
<!--main/templates/new.html-->
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Write</title>
    <!-- <link rel="stylesheet" href="./style.css"> -->
    <link rel="stylesheet" href="{% static 'main/css/new.css' %}">
</head>

<body>

    <main>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            
            <label for="title" id="title">제목:</label>
            <input type="text" id="title" name="title" maxlength="150"required="">
            <!-- <input type="text" name="title" maxlength="150" required="" id="id_title"> -->
            <br><br>
            <hr>
            
            <section class="inputs">
                <div class="name_input">
                    <label for="item"> 품목    </label>
                    <input type="text" id="item" name="item" maxlength="50" required="">
                    <!-- <input type="text" name="item" maxlength="50" required="" id="id_item"> -->
                </div>

                <div class="name_input">
                    <label for="link"> 링크    </label>
                    <input type="url" id="link" name="link"maxlength="300">
                    <!-- <input  name="link" maxlength="300" id="id_link"> -->
                </div>
                <div class="name_input">
                    <label for="category">카테고리</label>
                    <select name="category" required="" id="id_category">
                        <option value="" selected="">---------</option>
                      
                        <option value="Offline">오프라인</option>
                      
                        <option value="Online">온라인</option>
                      
                        <option value="Delivery">배달음식</option>
                      
                      </select>
                </div>
                
                

                <div class="name_input">
                    <label for="people">모집인원</label>
                    <input type="number" id="people" name="limit"value="1" min="0" required="">
                    <!-- <input type="number" name="limit" value="1" min="0" required="" id="id_limit"> -->
                </div>
                <!-- 이부분 백 완성 후 확인 -->
                <div class="name_input">
                    <label for="image">이미지 </label>
                    <input type="file" name="image"  accept="image/*" class="image-accept"  id="id_image">
                </div>
                
                
                <div class="name_input">
                    <div class="dead">
                        <label for="deadline">마감기한</label>
                        <input type="datetime-local" id="deadline" name="deadline">
                        <!-- <input type="text" name="deadline" id="id_deadline"> -->
                    </div>
                </div>
            </section>
                        <!-- <input type="text" id="bodytext" name="body" placeholder="내용을 입력하세요."> -->
            <textarea name="body" cols="40" id="bodytext" rows="10" required="" id="id_body"placeholder="내용을 입력하세요."></textarea>
            <button type="submit" id = "makechat">대기방 개설</button>
        </form>
    </main>
</body>

</html>
{% endblock %}